-- AlterTable
ALTER TABLE "Rider" ADD COLUMN "payModel" TEXT NOT NULL DEFAULT 'PERCENTAGE';
ALTER TABLE "Rider" ADD COLUMN "commissionRateBps" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Rider" ADD COLUMN "monthlySalary" INTEGER NOT NULL DEFAULT 0;
