import { Router } from "express";
import { requireAuth, requireRoles } from "../../middleware/auth.js";
import { validation } from "../../middleware/error.js";
import { asyncHandler } from "../../utils/async-handler.js";
import { ledgerSummary } from "../../controllers/finance.controller.js";
import { osHistoryRouter } from "./os-history.routes.js";
import { receiveOsReturnsBulk } from "../../controllers/finance.controller.js";
import { adjustment, amendOsSettlement, approveOsCutoverAdjustment, approveVariance, close, createExpense, createExpenseCategory, createOsPayment, createOsSettlement, declareSettlement, deliveryCollection, editOsSettlementDraft, expenseCategories, expenses, ledger, openingBalance, osAccountHistory, osAccounts, osPendingReturns, osSettlementDetail, osSettlementDrafts, osSettlementPreview, osSettlements, receiveOsReturn, reopen, replaceOsPayment, reversal, reverseOsSettlement, returnDeduction, riderOutstanding, savedOsSettlementDrafts, saveOsSettlementDraft, settlement, settlementPreview, voidOsPayment, walletTransfer } from "../../controllers/finance.controller.js";
import { createRiderSettlementValidators, declareRiderSettlementValidators, riderOutstandingValidators, riderSettlementPreviewValidators } from "../../validators/finance/rider-settlements.js";
import { approveCashbookVarianceValidators, cashbookAdjustmentValidators, closeCashbookValidators, openingBalanceValidators, reopenCashbookValidators, walletTransferValidators } from "../../validators/finance/cashbook.js";
import { createExpenseCategoryValidators, createExpenseValidators, listExpensesValidators } from "../../validators/finance/expenses.js";
import { deliveryCollectionValidators, ledgerListValidators, returnDeductionValidators, reversalValidators } from "../../validators/finance/ledger.js";
import { cutoverAdjustmentValidators, osAccountHistoryValidators, osAccountsValidators, osPaymentValidators, replaceOsPaymentValidators, voidOsPaymentValidators } from "../../validators/finance/os-accounts.js";
import { osPendingReturnsValidators, receiveOsReturnValidators, receiveOsReturnsBulkValidators } from "../../validators/finance/os-returns.js";
import { amendOsSettlementValidators, createOsSettlementValidators, editOsSettlementDraftValidators, osSettlementDetailValidators, osSettlementDraftListValidators, osSettlementListValidators, osSettlementPreviewValidators, reverseOsSettlementValidators, savedOsSettlementDraftListValidators, saveOsSettlementDraftValidators } from "../../validators/finance/os-settlement-routes.js";

export const financeRouter = Router();
financeRouter.use("/os-history", osHistoryRouter);
financeRouter.post("/os-returns/receive-bulk", requireAuth, requireRoles("SUPERADMIN", "FINANCE", "OPERATIONS_MANAGER"), receiveOsReturnsBulkValidators, validation, asyncHandler(receiveOsReturnsBulk));

financeRouter.get("/ledger", requireAuth, requireRoles("SUPERADMIN", "FINANCE", "OPERATIONS_MANAGER", "AUDITOR"), ledgerListValidators, validation, asyncHandler(ledger));
financeRouter.get("/ledger/summary", requireAuth, requireRoles("SUPERADMIN", "FINANCE", "OPERATIONS_MANAGER", "AUDITOR"), ledgerListValidators, validation, asyncHandler(ledgerSummary));
financeRouter.post("/ledger/delivery-collections", requireAuth, requireRoles("SUPERADMIN", "FINANCE", "OPERATIONS_MANAGER"), deliveryCollectionValidators, validation, asyncHandler(deliveryCollection));
financeRouter.post("/ledger/return-deductions", requireAuth, requireRoles("SUPERADMIN", "FINANCE", "OPERATIONS_MANAGER"), returnDeductionValidators, validation, asyncHandler(returnDeduction));
financeRouter.post("/ledger/reversals", requireAuth, requireRoles("SUPERADMIN", "FINANCE"), reversalValidators, validation, asyncHandler(reversal));
financeRouter.get("/os-accounts", requireAuth, requireRoles("SUPERADMIN", "FINANCE", "OPERATIONS_MANAGER", "AUDITOR"), osAccountsValidators, validation, asyncHandler(osAccounts));
financeRouter.get("/os-accounts/:shopId/history", requireAuth, requireRoles("SUPERADMIN", "FINANCE", "OPERATIONS_MANAGER", "AUDITOR"), osAccountHistoryValidators, validation, asyncHandler(osAccountHistory));
financeRouter.post("/os-accounts/cutover-adjustment", requireAuth, requireRoles("SUPERADMIN"), cutoverAdjustmentValidators, validation, asyncHandler(approveOsCutoverAdjustment));
financeRouter.post("/os-payments", requireAuth, requireRoles("SUPERADMIN", "FINANCE"), osPaymentValidators, validation, asyncHandler(createOsPayment));
financeRouter.post("/os-payments/:id/void", requireAuth, requireRoles("SUPERADMIN", "FINANCE"), voidOsPaymentValidators, validation, asyncHandler(voidOsPayment));
financeRouter.post("/os-payments/:id/replace", requireAuth, requireRoles("SUPERADMIN", "FINANCE"), replaceOsPaymentValidators, validation, asyncHandler(replaceOsPayment));
financeRouter.post("/rider-settlements", requireAuth, requireRoles("SUPERADMIN", "FINANCE", "OPERATIONS_MANAGER"), createRiderSettlementValidators, validation, asyncHandler(settlement));
financeRouter.get("/rider-settlements/preview", requireAuth, riderSettlementPreviewValidators, validation, asyncHandler(settlementPreview));
financeRouter.get("/rider-outstanding", requireAuth, requireRoles("SUPERADMIN", "FINANCE", "OPERATIONS_MANAGER"), riderOutstandingValidators, validation, asyncHandler(riderOutstanding));
financeRouter.get("/os-settlement-drafts", requireAuth, requireRoles("SUPERADMIN", "FINANCE", "OPERATIONS_MANAGER"), osSettlementDraftListValidators, validation, asyncHandler(osSettlementDrafts));
financeRouter.get("/os-settlement-drafts/saved", requireAuth, requireRoles("SUPERADMIN", "FINANCE", "OPERATIONS_MANAGER"), savedOsSettlementDraftListValidators, validation, asyncHandler(savedOsSettlementDrafts));
financeRouter.post("/os-settlement-drafts", requireAuth, requireRoles("SUPERADMIN", "FINANCE", "OPERATIONS_MANAGER"), saveOsSettlementDraftValidators, validation, asyncHandler(saveOsSettlementDraft));
financeRouter.patch("/os-settlement-drafts/:id", requireAuth, requireRoles("SUPERADMIN", "FINANCE", "OPERATIONS_MANAGER"), editOsSettlementDraftValidators, validation, asyncHandler(editOsSettlementDraft));
financeRouter.post("/os-settlements/preview", requireAuth, requireRoles("SUPERADMIN", "FINANCE", "OPERATIONS_MANAGER"), osSettlementPreviewValidators, validation, asyncHandler(osSettlementPreview));
financeRouter.get("/os-settlements", requireAuth, requireRoles("SUPERADMIN", "FINANCE", "OPERATIONS_MANAGER", "AUDITOR"), osSettlementListValidators, validation, asyncHandler(osSettlements));
financeRouter.get("/os-settlements/:id", requireAuth, requireRoles("SUPERADMIN", "FINANCE", "OPERATIONS_MANAGER", "AUDITOR"), osSettlementDetailValidators, validation, asyncHandler(osSettlementDetail));
financeRouter.post("/os-settlements", requireAuth, requireRoles("SUPERADMIN", "FINANCE", "OPERATIONS_MANAGER"), createOsSettlementValidators, validation, asyncHandler(createOsSettlement));
financeRouter.post("/os-settlements/:id/reversal", requireAuth, requireRoles("SUPERADMIN", "FINANCE"), reverseOsSettlementValidators, validation, asyncHandler(reverseOsSettlement));
financeRouter.patch("/os-settlements/:id", requireAuth, requireRoles("SUPERADMIN", "FINANCE"), amendOsSettlementValidators, validation, asyncHandler(amendOsSettlement));
financeRouter.get("/os-pending-returns", requireAuth, requireRoles("SUPERADMIN", "FINANCE", "OPERATIONS_MANAGER", "AUDITOR"), osPendingReturnsValidators, validation, asyncHandler(osPendingReturns));
financeRouter.post("/os-returns/receive", requireAuth, requireRoles("SUPERADMIN", "FINANCE", "OPERATIONS_MANAGER"), receiveOsReturnValidators, validation, asyncHandler(receiveOsReturn));
financeRouter.post("/rider-settlements/declarations", requireAuth, requireRoles("RIDER"), declareRiderSettlementValidators, validation, asyncHandler(declareSettlement));
financeRouter.post("/cashbook/close", requireAuth, requireRoles("SUPERADMIN", "FINANCE"), closeCashbookValidators, validation, asyncHandler(close));
financeRouter.post("/cashbook/variance-approval", requireAuth, requireRoles("SUPERADMIN", "FINANCE"), approveCashbookVarianceValidators, validation, asyncHandler(approveVariance));
financeRouter.post("/cashbook/reopen", requireAuth, requireRoles("SUPERADMIN"), reopenCashbookValidators, validation, asyncHandler(reopen));
financeRouter.post("/cashbook/opening-balances", requireAuth, requireRoles("SUPERADMIN", "FINANCE"), openingBalanceValidators, validation, asyncHandler(openingBalance));
financeRouter.post("/cashbook/transfers", requireAuth, requireRoles("SUPERADMIN", "FINANCE"), walletTransferValidators, validation, asyncHandler(walletTransfer));
financeRouter.post("/cashbook/adjustments", requireAuth, requireRoles("SUPERADMIN", "FINANCE"), cashbookAdjustmentValidators, validation, asyncHandler(adjustment));
financeRouter.get("/expense-categories", requireAuth, requireRoles("SUPERADMIN", "FINANCE", "OPERATIONS_MANAGER"), asyncHandler(expenseCategories));
financeRouter.post("/expense-categories", requireAuth, requireRoles("SUPERADMIN"), createExpenseCategoryValidators, validation, asyncHandler(createExpenseCategory));
financeRouter.get("/expenses", requireAuth, requireRoles("SUPERADMIN", "FINANCE", "OPERATIONS_MANAGER"), listExpensesValidators, validation, asyncHandler(expenses));
financeRouter.post("/expenses", requireAuth, requireRoles("SUPERADMIN", "FINANCE", "OPERATIONS_MANAGER"), createExpenseValidators, validation, asyncHandler(createExpense));
