import { Router } from "express";
import { requireAuth, requireRoles } from "../../middleware/auth.js";
import { validation } from "../../middleware/error.js";
import { asyncHandler } from "../../utils/async-handler.js";
import express from "express";
import { acknowledgeAlert, alerts, batchDetail, batches, bulkAssign, bulkCreateParcels, createBatch, downloadManifest, extendPendingReturn, linkParcels, postPickupAdvances, previewManifestImport, reassignParcel } from "../../controllers/operations.controller.js";
import { MAX_MANIFEST_BYTES } from "../../services/manifest-import.service.js";
import { alertIdValidation, batchIdValidation, bulkAssignmentValidation, bulkParcelCreateValidation, createBatchValidation, linkParcelsValidation, manifestDownloadValidation, parcelIdValidation, pendingReturnExtensionValidation, pickupAdvanceValidation, reassignParcelValidation } from "../../validators/operations.js";

export const operationsRouter = Router();
operationsRouter.get("/batches", requireAuth, requireRoles("SUPERADMIN", "OPERATIONS_MANAGER", "FINANCE", "DISPATCHER"), asyncHandler(batches));
operationsRouter.post("/batches", requireAuth, requireRoles("SUPERADMIN", "OPERATIONS_MANAGER", "DISPATCHER"), createBatchValidation, validation, asyncHandler(createBatch));
operationsRouter.get("/batches/:id", requireAuth, requireRoles("SUPERADMIN","OPERATIONS_MANAGER","FINANCE","DISPATCHER"), batchIdValidation, validation, asyncHandler(batchDetail));
operationsRouter.post("/batches/:id/parcels/bulk", requireAuth, requireRoles("SUPERADMIN","OPERATIONS_MANAGER","DISPATCHER"), bulkParcelCreateValidation, validation, asyncHandler(bulkCreateParcels));
operationsRouter.post("/batches/:id/manifest-preview", requireAuth, requireRoles("SUPERADMIN","OPERATIONS_MANAGER","DISPATCHER"), express.raw({type:"application/pdf",limit:MAX_MANIFEST_BYTES}), asyncHandler(previewManifestImport));
operationsRouter.post("/batches/:id/pickup-advances", requireAuth, requireRoles("SUPERADMIN", "FINANCE"), batchIdValidation, pickupAdvanceValidation, validation, asyncHandler(postPickupAdvances));
operationsRouter.post("/parcels/bulk-assign", requireAuth, requireRoles("SUPERADMIN", "OPERATIONS_MANAGER", "DISPATCHER"), bulkAssignmentValidation, validation, asyncHandler(bulkAssign));
operationsRouter.post("/parcels/manifest", requireAuth, requireRoles("SUPERADMIN", "OPERATIONS_MANAGER", "DISPATCHER"), manifestDownloadValidation, validation, asyncHandler(downloadManifest));
operationsRouter.post("/parcels/link", requireAuth, requireRoles("SUPERADMIN", "OPERATIONS_MANAGER", "DISPATCHER"), linkParcelsValidation, validation, asyncHandler(linkParcels));
operationsRouter.post("/parcels/:id/reassign", requireAuth, requireRoles("SUPERADMIN", "OPERATIONS_MANAGER", "DISPATCHER"), parcelIdValidation, reassignParcelValidation, validation, asyncHandler(reassignParcel));
operationsRouter.post("/parcels/:id/return-extension", requireAuth, requireRoles("SUPERADMIN", "OPERATIONS_MANAGER"), parcelIdValidation, pendingReturnExtensionValidation, validation, asyncHandler(extendPendingReturn));
operationsRouter.get("/alerts", requireAuth, requireRoles("SUPERADMIN", "OPERATIONS_MANAGER"), asyncHandler(alerts));
operationsRouter.post("/alerts/:id/acknowledge", requireAuth, requireRoles("SUPERADMIN", "OPERATIONS_MANAGER"), alertIdValidation, validation, asyncHandler(acknowledgeAlert));
