import { useMutation, useQuery } from "@tanstack/react-query";
import { Download } from "lucide-react";
import { useState } from "react";
import { useTranslation } from "react-i18next";
import { useAuth } from "@/app/auth";
import { api, apiRaw } from "@/lib/api";

type ReportKey = "monthly-operations" | "returns" | "rider-performance" | "os-statements";
type Masters = { hubs?: Array<{id:string;name:string}>; shops?: Array<{id:string;name:string}>; riders?: Array<{id:string;user:{name:string}}> };
type Monthly = { totals:{statusTransitions:number;uniqueParcels:number};transitionCounts:Record<string,number>;currentStatusCounts:Record<string,number> };
type Returns = { totals:{events:number;uniqueParcels:number;pendingReturnEvents:number;returnedEvents:number;advanceAmount:number};events:Array<{id:string;occurredAt:string;fromStatus:string|null;toStatus:string;reasonCode:string|null;overdue:boolean;parcel:{trackingNumber:string;orderId:string|null;status:string;advanceAmount:number;batch:{label:string}}}> };
type RiderPerformance = { totals:{riders:number;completedWays:number;delivered:number;commissionAmount:number};riders:Array<{riderId:string;riderName:string;completedWays:number;delivered:number;partial:number;failed:number;rejected:number;superseded:number;commissionAmount:number}> };
type OsStatements = { totals:{records:number;settlements:number;reversedOrReplaced:number;grossCollectedCod:number;advanceDeduction:number;returnDeduction:number;deliveryFeeDeduction:number;adjustmentAmount:number;netAmount:number};settlements:Array<{id:string;businessDate:string;status:string;grossCollectedCod:number;advanceDeduction:number;returnDeduction:number;deliveryFeeDeduction:number;adjustmentAmount:number;netAmount:number;wallet:string;shop:{name:string}}> };

const tabs:ReportKey[]=["monthly-operations","returns","rider-performance","os-statements"];
const csvReports=new Set<ReportKey>(["returns","rider-performance","os-statements"]);
const control="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-[#1598ef] dark:border-white/10 dark:bg-[#121416]";
const today=()=>new Date().toISOString().slice(0,10);
const money=(value:number)=>`${value.toLocaleString()} MMK`;

export function DetailedReportsPanel(){
 const {t}=useTranslation();const {user}=useAuth();const [tab,setTab]=useState<ReportKey>("monthly-operations");
 const [draft,setDraft]=useState({from:today().slice(0,7)+"-01",to:today(),hubId:"",shopId:"",riderId:""});const [filters,setFilters]=useState(draft);
 const masters=useQuery({queryKey:["master-data"],queryFn:()=>api<Masters>("/master-data").then(r=>r.data)});
 const params=new URLSearchParams({from:filters.from,to:filters.to});for(const key of ["hubId","shopId","riderId"] as const)if(filters[key])params.set(key,filters[key]);
 const enabled=Boolean(filters.from&&filters.to)&&(user?.role!=="SUPERADMIN"||Boolean(filters.hubId));
 const report=useQuery({queryKey:["detailed-report",tab,params.toString()],enabled,queryFn:()=>api<Monthly|Returns|RiderPerformance|OsStatements>(`/reports/${tab}?${params}`).then(r=>r.data)});
 const csv=useMutation({mutationFn:()=>apiRaw(`/reports/${tab}?${params}&format=csv`),onSuccess:async response=>{const url=URL.createObjectURL(await response.blob());const link=document.createElement("a");link.href=url;link.download=`${tab}-${filters.from}-${filters.to}.csv`;link.click();URL.revokeObjectURL(url)}});
 const summary=(items:Array<[string,number|string]>)=><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{items.map(([label,value])=><div key={label} className="rounded-xl border border-slate-100 p-4 dark:border-white/10"><p className="text-xs text-slate-500">{t(label)}</p><p className="mt-1 text-xl font-bold">{value}</p></div>)}</div>;
 const tableClass="mt-4 w-full min-w-[760px] text-left text-sm";
 return <section className="mt-6 rounded-2xl bg-white p-6 shadow-sm dark:bg-[#181a1d]" aria-labelledby="detailed-reports-heading">
  <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 id="detailed-reports-heading" className="font-display text-lg font-bold">{t("operationalReports")}</h2><p className="text-sm text-slate-500">{t("operationalReportsDescription")}</p></div>{csvReports.has(tab)&&<button type="button" disabled={!report.data||csv.isPending} onClick={()=>csv.mutate()} className="rounded-xl border border-[#1598ef] px-4 py-2 text-sm font-bold text-[#0787df] disabled:opacity-40"><Download className="mr-2 inline" size={16}/>{csv.isPending?t("loading"):t("downloadCsv")}</button>}</div>
  <div role="tablist" aria-label={t("operationalReports")} className="mt-5 flex flex-wrap gap-2">{tabs.map(key=><button key={key} type="button" role="tab" aria-selected={tab===key} onClick={()=>setTab(key)} className={`rounded-lg px-3 py-2 text-sm font-bold ${tab===key?"bg-[#1598ef] text-white":"bg-slate-100 text-slate-600 dark:bg-white/10 dark:text-slate-300"}`}>{t(`report_${key}`)}</button>)}</div>
  <form onSubmit={event=>{event.preventDefault();setFilters(draft)}} className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-6">
   <label className="text-xs font-bold text-slate-500">{t("dateFrom")}<input aria-label={`${t("operationalReports")} ${t("dateFrom")}`} required type="date" value={draft.from} onChange={e=>setDraft(v=>({...v,from:e.target.value}))} className={`${control} mt-1 w-full`}/></label>
   <label className="text-xs font-bold text-slate-500">{t("dateTo")}<input aria-label={`${t("operationalReports")} ${t("dateTo")}`} required type="date" value={draft.to} onChange={e=>setDraft(v=>({...v,to:e.target.value}))} className={`${control} mt-1 w-full`}/></label>
   <label className="text-xs font-bold text-slate-500">{t("hub")}<select aria-label={`${t("operationalReports")} ${t("hub")}`} required={user?.role==="SUPERADMIN"} value={draft.hubId} onChange={e=>setDraft(v=>({...v,hubId:e.target.value}))} className={`${control} mt-1 w-full`}><option value="">{user?.role==="SUPERADMIN"?t("selectHub"):t("assignedHub")}</option>{(masters.data?.hubs??[]).map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label>
   <label className="text-xs font-bold text-slate-500">{t("onlineShop")}<select aria-label={`${t("operationalReports")} ${t("onlineShop")}`} value={draft.shopId} onChange={e=>setDraft(v=>({...v,shopId:e.target.value}))} className={`${control} mt-1 w-full`}><option value="">{t("all")}</option>{(masters.data?.shops??[]).map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label>
   <label className="text-xs font-bold text-slate-500">{t("rider")}<select aria-label={`${t("operationalReports")} ${t("rider")}`} value={draft.riderId} onChange={e=>setDraft(v=>({...v,riderId:e.target.value}))} className={`${control} mt-1 w-full`}><option value="">{t("allRiders")}</option>{(masters.data?.riders??[]).map(row=><option key={row.id} value={row.id}>{row.user.name}</option>)}</select></label>
   <button className="self-end rounded-xl bg-[#1598ef] px-4 py-2.5 text-sm font-bold text-white">{t("runReport")}</button>
  </form>
  {!enabled?<p className="mt-6 rounded-xl bg-sky-50 p-4 text-sm text-sky-800 dark:bg-sky-950/30 dark:text-sky-200">{t("selectHubForReport")}</p>:report.isLoading?<p role="status" className="py-10 text-center">{t("loading")}</p>:report.isError?<div role="alert" className="mt-6 rounded-xl bg-rose-50 p-4 text-sm text-rose-700 dark:bg-rose-950/30 dark:text-rose-200"><p>{t("detailedReportLoadError")}</p><button type="button" onClick={()=>void report.refetch()} className="mt-2 font-bold underline">{t("retry")}</button></div>:report.data?<div className="mt-6" role="tabpanel">
   {tab==="monthly-operations"&&(()=>{const data=report.data as Monthly;const rows=Object.entries(data.transitionCounts??{});return <>{summary([["statusTransitions",data.totals?.statusTransitions??0],["uniqueParcels",data.totals?.uniqueParcels??0]])}{!rows.length?<p className="py-8 text-center text-slate-400">{t("noReportData")}</p>:<div className="overflow-x-auto"><table className={tableClass}><thead><tr><th>{t("status")}</th><th className="text-right">{t("transitions")}</th><th className="text-right">{t("currentParcelCount")}</th></tr></thead><tbody>{rows.map(([status,count])=><tr key={status} className="border-b border-slate-100 dark:border-white/10"><td className="py-3">{status.replaceAll("_"," ")}</td><td className="text-right">{count}</td><td className="text-right">{data.currentStatusCounts?.[status]??0}</td></tr>)}</tbody></table></div>}</>})()}
   {tab==="returns"&&(()=>{const data=report.data as Returns;return <>{summary([["returnEvents",data.totals.events],["uniqueParcels",data.totals.uniqueParcels],["pendingReturnEvents",data.totals.pendingReturnEvents],["returnedEvents",data.totals.returnedEvents],["returnAdvanceAmount",money(data.totals.advanceAmount)]])}{!data.events.length?<p className="py-8 text-center text-slate-400">{t("noReportData")}</p>:<div className="overflow-x-auto"><table className={tableClass}><thead><tr><th>{t("occurredAt")}</th><th>{t("tracking")}</th><th>{t("status")}</th><th>{t("reason")}</th><th className="text-right">{t("originalAdvance")}</th></tr></thead><tbody>{data.events.map(row=><tr key={row.id} className="border-b border-slate-100 dark:border-white/10"><td className="py-3">{new Date(row.occurredAt).toLocaleString()}</td><td>{row.parcel.trackingNumber}</td><td>{row.fromStatus??"—"} → {row.toStatus}{row.overdue&&<span className="ml-2 text-xs font-bold text-rose-600">{t("overdue")}</span>}</td><td>{row.reasonCode??"—"}</td><td className="text-right">{money(row.parcel.advanceAmount)}</td></tr>)}</tbody></table></div>}</>})()}
   {tab==="rider-performance"&&(()=>{const data=report.data as RiderPerformance;return <>{summary([["riders",data.totals.riders],["completedWays",data.totals.completedWays],["delivered",data.totals.delivered],["commission",money(data.totals.commissionAmount)]])}{!data.riders.length?<p className="py-8 text-center text-slate-400">{t("noReportData")}</p>:<div className="overflow-x-auto"><table className={tableClass}><thead><tr><th>{t("rider")}</th><th className="text-right">{t("completedWays")}</th><th className="text-right">{t("delivered")}</th><th className="text-right">{t("partial")}</th><th className="text-right">{t("failed")}</th><th className="text-right">{t("commission")}</th></tr></thead><tbody>{data.riders.map(row=><tr key={row.riderId} className="border-b border-slate-100 dark:border-white/10"><td className="py-3 font-semibold">{row.riderName}</td><td className="text-right">{row.completedWays}</td><td className="text-right">{row.delivered}</td><td className="text-right">{row.partial}</td><td className="text-right">{row.failed}</td><td className="text-right">{money(row.commissionAmount)}</td></tr>)}</tbody></table></div>}</>})()}
   {tab==="os-statements"&&(()=>{const data=report.data as OsStatements;return <>{summary([["settlementRecords",data.totals.records],["activeSettlements",data.totals.settlements],["reversedOrReplaced",data.totals.reversedOrReplaced],["netAmount",money(data.totals.netAmount)]])}{!data.settlements.length?<p className="py-8 text-center text-slate-400">{t("noReportData")}</p>:<div className="overflow-x-auto"><table className={tableClass}><thead><tr><th>{t("businessDate")}</th><th>{t("onlineShop")}</th><th>{t("status")}</th><th className="text-right">{t("grossCollectedCod")}</th><th className="text-right">{t("deductions")}</th><th className="text-right">{t("netAmount")}</th></tr></thead><tbody>{data.settlements.map(row=><tr key={row.id} className="border-b border-slate-100 dark:border-white/10"><td className="py-3">{row.businessDate.slice(0,10)}</td><td>{row.shop.name}</td><td>{row.status}</td><td className="text-right">{money(row.grossCollectedCod)}</td><td className="text-right">{money(row.advanceDeduction+row.returnDeduction+row.deliveryFeeDeduction)}</td><td className="text-right font-bold">{money(row.netAmount)}</td></tr>)}</tbody></table></div>}</>})()}
  </div>:null}
 </section>;
}
