import {useQuery} from "@tanstack/react-query";
import {History,X} from "lucide-react";
import {useTranslation} from "react-i18next";
import {api} from "@/lib/api";

type AuditRow={id:string;createdAt:string;before:Record<string,unknown>;after:Record<string,unknown>;actor:{id:string;name:string;role:string}};

export function ParcelFieldHistory({parcel,onClose}:{parcel:{id:string;trackingNumber:string};onClose:()=>void}){
 const {t,i18n}=useTranslation();
 const history=useQuery({queryKey:["parcel-field-history",parcel.id],queryFn:()=>api<AuditRow[]>(`/parcels/${encodeURIComponent(parcel.id)}/field-history`).then(r=>r.data)});
 return <div role="dialog" aria-modal="true" aria-labelledby="parcel-field-history-title" className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4"><section className="max-h-[88vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl dark:bg-[#181a1d]"><div className="flex items-start justify-between gap-4"><div><h2 id="parcel-field-history-title" className="flex items-center gap-2 font-display text-xl font-bold"><History size={20}/>{t("parcelFieldHistory")}</h2><p className="mt-1 text-sm text-slate-500">{parcel.trackingNumber}</p></div><button type="button" aria-label={t("close")} onClick={onClose} className="rounded-lg border p-2 dark:border-white/10"><X size={16}/></button></div>
 {history.isLoading?<p className="py-10 text-center text-sm text-slate-400">{t("loading")}</p>:history.isError?<div className="py-10 text-center"><p role="alert" className="text-sm text-rose-600">{t("fieldHistoryLoadError")}</p><button type="button" onClick={()=>void history.refetch()} className="mt-2 text-sm font-bold text-[#0787df]">{t("retry")}</button></div>:!history.data?.length?<p className="py-10 text-center text-sm text-slate-400">{t("noFieldHistory")}</p>:<ol className="mt-6 space-y-4">{history.data.map(row=><li key={row.id} className="rounded-xl border border-slate-200 p-4 dark:border-white/10"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-bold">{row.actor.name}<span className="ml-2 text-xs font-medium text-slate-400">{t(`role_${row.actor.role}`)}</span></p><time className="text-xs text-slate-500" dateTime={row.createdAt}>{new Intl.DateTimeFormat(i18n.resolvedLanguage==="my"?"my-MM":"en-GB",{dateStyle:"medium",timeStyle:"short"}).format(new Date(row.createdAt))}</time></div><dl className="mt-3 divide-y divide-slate-100 dark:divide-white/5">{changedKeys(row).map(key=><div key={key} className="grid gap-1 py-2 text-sm sm:grid-cols-[minmax(8rem,1fr)_2fr_2fr]"><dt className="font-semibold">{fieldLabel(key,t)}</dt><dd><span className="mr-1 text-xs text-slate-400">{t("before")}</span><span className="break-words line-through decoration-rose-400">{formatValue(row.before[key])}</span></dd><dd><span className="mr-1 text-xs text-slate-400">{t("after")}</span><span className="break-words font-semibold text-emerald-700 dark:text-emerald-300">{formatValue(row.after[key])}</span></dd></div>)}</dl></li>)}</ol>}
 </section></div>
}
function changedKeys(row:AuditRow){return Array.from(new Set([...Object.keys(row.before),...Object.keys(row.after)]));}
function formatValue(value:unknown){if(value===null||value===undefined||value==="")return "—";if(typeof value==="object")return JSON.stringify(value);return String(value);}
function fieldLabel(key:string,t:(key:string)=>string){const known:Record<string,string>={orderId:"orderId",customerName:"customer",customerPhone:"customerPhone",address:"address",townshipId:"township",zoneId:"zone",codAmount:"cod",deliveryFee:"deliveryFee"};return known[key]?t(known[key]):key.replace(/([a-z])([A-Z])/g,"$1 $2");}
