ALTER TABLE "User" ADD COLUMN "username" TEXT;
CREATE UNIQUE INDEX "User_username_key" ON "User"("username");
ALTER TABLE "Batch" ADD COLUMN "advancePaid" INTEGER NOT NULL DEFAULT 0;
UPDATE "Batch" b SET "advancePaid"=(SELECT COALESCE(SUM(p."advanceAmount"),0) FROM "Parcel" p WHERE p."batchId"=b."id");
DROP INDEX "Batch_shopId_pickupDate_key";
CREATE INDEX "Batch_shopId_pickupDate_idx" ON "Batch"("shopId", "pickupDate");
CREATE TABLE "RegionState" ("id" TEXT PRIMARY KEY,"code" TEXT NOT NULL UNIQUE,"nameEn" TEXT NOT NULL,"nameMy" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "District" ("id" TEXT PRIMARY KEY,"code" TEXT NOT NULL UNIQUE,"regionStateId" TEXT NOT NULL REFERENCES "RegionState"("id"),"nameEn" TEXT NOT NULL,"nameMy" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "District_regionStateId_nameEn_key" ON "District"("regionStateId","nameEn");
CREATE TABLE "Township" ("id" TEXT PRIMARY KEY,"code" TEXT NOT NULL UNIQUE,"districtId" TEXT NOT NULL REFERENCES "District"("id"),"nameEn" TEXT NOT NULL,"nameMy" TEXT,"deliveryFee" INTEGER,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "Township_districtId_nameEn_key" ON "Township"("districtId","nameEn");
ALTER TABLE "Zone" ADD COLUMN "townshipId" TEXT REFERENCES "Township"("id");
CREATE INDEX "Zone_townshipId_idx" ON "Zone"("townshipId");
ALTER TABLE "Parcel" ADD COLUMN "townshipId" TEXT REFERENCES "Township"("id");
CREATE INDEX "Parcel_townshipId_idx" ON "Parcel"("townshipId");
ALTER TABLE "Parcel" ALTER COLUMN "deliveryFee" DROP NOT NULL;
CREATE TABLE "ExpenseCategory" ("id" TEXT PRIMARY KEY,"code" TEXT NOT NULL UNIQUE,"nameEn" TEXT NOT NULL,"nameMy" TEXT NOT NULL,"active" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "ExpenseEntry" ("id" TEXT PRIMARY KEY,"hubId" TEXT NOT NULL,"categoryId" TEXT NOT NULL REFERENCES "ExpenseCategory"("id"),"wallet" TEXT NOT NULL,"businessDate" TIMESTAMP(3) NOT NULL,"description" TEXT NOT NULL,"amount" INTEGER NOT NULL,"actorId" TEXT NOT NULL,"journalEntryId" TEXT NOT NULL UNIQUE,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX "ExpenseEntry_hubId_businessDate_idx" ON "ExpenseEntry"("hubId","businessDate");
INSERT INTO "ExpenseCategory"("id","code","nameEn","nameMy","updatedAt") VALUES ('expense_rent','RENT','Rent','အိမ်ငှားခ',CURRENT_TIMESTAMP),('expense_salary','SALARY','Salary','လစာ',CURRENT_TIMESTAMP),('expense_utilities','UTILITIES','Utilities','အသုံးစရိတ်များ',CURRENT_TIMESTAMP),('expense_other','OTHER','Other','အခြား',CURRENT_TIMESTAMP);
