import type { RequestHandler } from "express";
import * as riderSettlementService from "../services/finance/rider-settlements.js";
import * as osSettlementService from "../services/finance/os-settlements.js";
import * as osSettlementDraftService from "../services/finance/os-settlement-drafts.js";
import * as osReturnService from "../services/finance/os-returns.js";
import * as cashbookCloseService from "../services/finance/cashbook-close.js";
import * as ledgerService from "../services/ledger.service.js";
import * as osAccountService from "../services/os-account.service.js";
import * as expenseService from "../services/finance/expenses.js";
import * as cashbookPostingService from "../services/finance/cashbook-postings.js";

const actor = (req: Parameters<RequestHandler>[0]) => ({ id: req.auth!.sub, role: req.auth!.role });

export const settlement: RequestHandler = async (req, res) => res.status(201).json({ success: true, data: await riderSettlementService.createRiderSettlement(req.body, actor(req)) });
export const settlementPreview: RequestHandler = async (req, res) => res.json({ success: true, data: await riderSettlementService.previewRiderSettlement({ businessDate: String(req.query.businessDate), riderId: typeof req.query.riderId === "string" ? req.query.riderId : undefined }, actor(req)) });
export const riderOutstanding: RequestHandler = async (req, res) => res.json({ success: true, data: await riderSettlementService.listRiderOutstanding({ businessDate: String(req.query.businessDate) }, actor(req)) });
export const osSettlementDrafts: RequestHandler = async (req, res) => res.json({ success: true, data: await osSettlementService.listOsSettlementDrafts({ shopId: typeof req.query.shopId === "string" ? req.query.shopId : undefined }, actor(req)) });
export const savedOsSettlementDrafts: RequestHandler = async (req, res) => res.json({ success: true, data: await osSettlementDraftService.listSavedOsSettlementDrafts({ shopId: typeof req.query.shopId === "string" ? req.query.shopId : undefined, hubId: typeof req.query.hubId === "string" ? req.query.hubId : undefined }, actor(req)) });
export const saveOsSettlementDraft: RequestHandler = async (req, res) => res.status(201).json({ success: true, data: await osSettlementDraftService.createOsSettlementDraft(req.body, actor(req)) });
export const editOsSettlementDraft: RequestHandler = async (req, res) => res.json({ success: true, data: await osSettlementDraftService.updateOsSettlementDraft({ id: String(req.params.id), ...req.body }, actor(req)) });
export const osSettlementPreview: RequestHandler = async (req, res) => res.json({ success: true, data: await osSettlementService.previewOsSettlement(req.body, actor(req)) });
export const createOsSettlement: RequestHandler = async (req, res) => res.status(201).json({ success: true, data: await osSettlementService.postOsSettlement(req.body, actor(req)) });
export const osSettlements: RequestHandler = async (req, res) => res.json({ success: true, data: await osSettlementService.listOsSettlements({ shopId: typeof req.query.shopId === "string" ? req.query.shopId : undefined, hubId: typeof req.query.hubId === "string" ? req.query.hubId : undefined }, actor(req)) });
export const osSettlementDetail: RequestHandler = async (req, res) => res.json({ success: true, data: await osSettlementService.getOsSettlement(String(req.params.id), actor(req)) });
export const reverseOsSettlement: RequestHandler = async (req, res) => res.json({ success: true, data: await osSettlementService.reverseOsSettlement({ id: String(req.params.id), ...req.body }, actor(req)) });
export const amendOsSettlement: RequestHandler = async (req, res) => res.status(201).json({ success: true, data: await osSettlementService.amendOsSettlement({ id: String(req.params.id), ...req.body }, actor(req)) });
export const osPendingReturns: RequestHandler = async (req, res) => res.json({ success: true, data: await osReturnService.listOsPendingReturns({ shopId: typeof req.query.shopId === "string" ? req.query.shopId : undefined, hubId: typeof req.query.hubId === "string" ? req.query.hubId : undefined }, actor(req)) });
export const receiveOsReturn: RequestHandler = async (req, res) => {
  const data = await osReturnService.receiveOsReturn(req.body, actor(req));
  const status = data.alreadyReceived ? 200 : 201;
  res.status(status).json({ success: true, data });
};
export const declareSettlement: RequestHandler = async (req, res) => res.status(201).json({ success: true, data: await riderSettlementService.declareRiderSettlement(req.body, actor(req)) });
export const close: RequestHandler = async (req, res) => res.json({ success: true, data: await cashbookCloseService.closeCashbook(req.body, actor(req)) });
export const approveVariance: RequestHandler = async (req, res) => res.json({ success: true, data: await cashbookCloseService.approveCashbookVariance(req.body, actor(req)) });
export const reopen: RequestHandler = async (req, res) => res.json({ success: true, data: await cashbookCloseService.reopenCashbook(req.body, actor(req)) });
export const openingBalance: RequestHandler = async (req, res) => res.status(201).json({ success: true, data: await cashbookPostingService.postOpeningBalance(req.body, actor(req)) });
export const walletTransfer: RequestHandler = async (req, res) => res.status(201).json({ success: true, data: await cashbookPostingService.postWalletTransfer(req.body, actor(req)) });
export const adjustment: RequestHandler = async (req, res) => res.status(201).json({ success: true, data: await cashbookPostingService.postCashbookAdjustment(req.body, actor(req)) });
export const expenseCategories: RequestHandler = async (req, res) => res.json({ success: true, data: await expenseService.listExpenseCategories(actor(req)) });
export const createExpenseCategory: RequestHandler = async (req, res) => res.status(201).json({ success: true, data: await expenseService.createExpenseCategory(req.body, actor(req)) });
export const expenses: RequestHandler = async (req, res) => res.json({ success: true, data: await expenseService.listExpenses({ businessDate: typeof req.query.businessDate === "string" ? req.query.businessDate : undefined, hubId: typeof req.query.hubId === "string" ? req.query.hubId : undefined, limit: typeof req.query.limit === "number" ? req.query.limit : typeof req.query.limit === "string" ? Number(req.query.limit) : undefined }, actor(req)) });
export const createExpense: RequestHandler = async (req, res) => res.status(201).json({ success: true, data: await expenseService.postExpense(req.body, actor(req)) });
export const ledger: RequestHandler = async (req, res) => res.json({ success: true, data: await ledgerService.getLedgerReport(req.query, actor(req)) });
export const ledgerSummary: RequestHandler = async (req, res) => res.json({ success: true, data: await ledgerService.getLedgerSummary(req.query, actor(req)) });
export const deliveryCollection: RequestHandler = async (req, res) => res.status(201).json({ success: true, data: await ledgerService.postDeliveryCollection(req.body, actor(req)) });
export const returnDeduction: RequestHandler = async (req, res) => res.status(201).json({ success: true, data: await ledgerService.postReturnDeduction(req.body, actor(req)) });
export const reversal: RequestHandler = async (req, res) => res.status(201).json({ success: true, data: await ledgerService.reverseJournalEntry(req.body, actor(req)) });
export const osAccounts: RequestHandler = async (req, res) => res.json({ success: true, data: await osAccountService.listOsAccounts({ shopId: typeof req.query.shopId === "string" ? req.query.shopId : undefined, hubId: typeof req.query.hubId === "string" ? req.query.hubId : undefined }, actor(req)) });
export const osAccountHistory: RequestHandler = async (req, res) => res.json({ success: true, data: await osAccountService.osAccountHistory(String(req.params.shopId), { hubId: typeof req.query.hubId === "string" ? req.query.hubId : undefined }, actor(req)) });
export const approveOsCutoverAdjustment: RequestHandler = async (req, res) => res.status(201).json({ success: true, data: await osAccountService.approveCutoverAdjustment(req.body, actor(req)) });
export const createOsPayment: RequestHandler = async (req, res) => res.status(201).json({ success: true, data: await osAccountService.postOsPayment(req.body, actor(req)) });
export const voidOsPayment: RequestHandler = async (req, res) => res.json({ success: true, data: await osAccountService.voidOsPayment({ id: String(req.params.id), ...req.body }, actor(req)) });
export const replaceOsPayment: RequestHandler = async (req, res) => res.status(201).json({ success: true, data: await osAccountService.replaceOsPayment({ id: String(req.params.id), ...req.body }, actor(req)) });
import { receiveOsReturnsBulk as receiveManyReturns } from "../services/finance/os-returns.js";
export const receiveOsReturnsBulk: import("express").RequestHandler = async (req, res) => res.json({ success: true, data: await receiveManyReturns(req.body, { id: req.auth!.sub, role: req.auth!.role }) });
