import type { RequestHandler } from "express";
import * as service from "../services/master-data.service.js";
const actor = (req: Parameters<RequestHandler>[0]) => ({ id: req.auth!.sub, role: req.auth!.role });
export const list: RequestHandler = async (req,res) => res.json({success:true,data:await service.listMasterData(actor(req))});
export const createHub: RequestHandler = async (req,res) => res.status(201).json({success:true,data:await service.createHub(req.body,actor(req))});
export const createShop: RequestHandler = async (req,res) => res.status(201).json({success:true,data:await service.createShop(req.body,actor(req))});
export const listShops: RequestHandler = async (req,res) => res.json({success:true,data:await service.listShops(actor(req))});
export const getShop: RequestHandler = async (req,res) => res.json({success:true,data:await service.getShop(String(req.params.id),actor(req))});
export const createZone: RequestHandler = async (req,res) => res.status(201).json({success:true,data:await service.createZone(req.body,actor(req))});
export const createRider: RequestHandler = async (req,res) => res.status(201).json({success:true,data:await service.createRider(req.body,actor(req))});
export const updateRider: RequestHandler = async (req,res) => res.json({success:true,data:await service.updateRider(String(req.params.id),req.body,actor(req))});
export const dashboard: RequestHandler = async (req,res) => res.json({success:true,data:await service.dashboardOverview(actor(req))});
export const listReasonCodes: RequestHandler = async (req,res) => res.json({success:true,data:await service.listReasonCodes(actor(req), typeof req.query.outcome === "string" ? req.query.outcome : undefined)});
export const createReasonCode: RequestHandler = async (req,res) => res.status(201).json({success:true,data:await service.createReasonCode(req.body,actor(req))});
export const updateReasonCode: RequestHandler = async (req,res) => res.json({success:true,data:await service.updateReasonCode(String(req.params.id),req.body,actor(req))});
export const listRegions:RequestHandler=async(req,res)=>res.json({success:true,data:await service.listRegions(actor(req))});
export const listDistricts:RequestHandler=async(req,res)=>res.json({success:true,data:await service.listDistricts(String(req.query.regionStateId),actor(req))});
export const listTownships:RequestHandler=async(req,res)=>res.json({success:true,data:await service.listTownships(typeof req.query.districtId==="string"?req.query.districtId:undefined,actor(req))});
export const listZones:RequestHandler=async(req,res)=>res.json({success:true,data:await service.listZones(String(req.query.townshipId),typeof req.query.hubId==="string"?req.query.hubId:undefined,actor(req))});
export const updateTownshipDeliveryFees:RequestHandler=async(req,res)=>res.json({success:true,data:await service.updateTownshipDeliveryFees(req.body,actor(req))});
export const importLocations:RequestHandler=async(req,res)=>res.status(201).json({success:true,data:await service.importLocations(req.body,actor(req))});
