import {fireEvent,render,screen,waitFor,within} from "@testing-library/react";
import {QueryClient,QueryClientProvider} from "@tanstack/react-query";
import {MemoryRouter} from "react-router-dom";
import {describe,expect,it,vi} from "vitest";
import "@/i18n";
import {Dashboard} from "./dashboard";
const apiMock=vi.hoisted(()=>vi.fn());vi.mock("@/lib/api",()=>({api:apiMock}));
describe("Dashboard batch creation",()=>{it("creates batch metadata first without parcel or wallet fields",async()=>{apiMock.mockImplementation((path:string)=>{if(path==="/master-data/dashboard")return Promise.resolve({data:{totalParcels:0,delivered:0,pendingReturn:0,cashCollected:0,grossProfit:0,batches:[]}});if(path==="/master-data")return Promise.resolve({data:{hubs:[{id:"hub-1",name:"Main Hub"}],shops:[{id:"shop-1",name:"Shop One"}]}});return Promise.resolve({data:{id:"batch-1"}})});const client=new QueryClient({defaultOptions:{queries:{retry:false}}});render(<MemoryRouter><QueryClientProvider client={client}><Dashboard/></QueryClientProvider></MemoryRouter>);fireEvent.click(await screen.findByRole("button",{name:/create batch/i}));const dialog=screen.getByRole("dialog");fireEvent.change(within(dialog).getByLabelText("Online shop"),{target:{value:"shop-1"}});fireEvent.change(within(dialog).getByLabelText("Hub"),{target:{value:"hub-1"}});fireEvent.change(within(dialog).getByLabelText("Batch label"),{target:{value:"Morning pickup"}});fireEvent.change(within(dialog).getByLabelText("Total advance paid"),{target:{value:"50000"}});expect(within(dialog).queryByLabelText("Funding wallet")).not.toBeInTheDocument();expect(within(dialog).queryByLabelText("Tracking")).not.toBeInTheDocument();fireEvent.click(within(dialog).getByRole("button",{name:"Save and add parcels"}));await waitFor(()=>expect(apiMock).toHaveBeenCalledWith("/operations/batches",expect.objectContaining({method:"POST",body:expect.stringContaining('"shopId":"shop-1"')})));});});

describe("Dashboard finance and operations visibility",()=>{it("shows backend-calculated totals and actionable deep links",async()=>{apiMock.mockImplementation((path:string)=>path==="/master-data/dashboard"?Promise.resolve({data:{totalParcels:12,delivered:8,pendingReturn:2,grossProfit:7000,batches:[],riderOutstanding:400000,unsettledRiderCount:3,unsettledOnlineShopBatches:2,codCollectedToday:900000,deliveryFeesToday:50000,walletBalances:{cash:100000,kbzPay:200000,wavePay:300000},returnsDue:4,returnsOverdue:1,failedPartialAlerts:5,expenseTotalToday:10000,profitComponents:{deliveryFeeRevenue:50000,riderCommissionExpense:33000,expenses:10000},deepLinks:{riderOutstanding:"/finance#rider-outstanding",onlineShopSettlements:"/finance#os-settlements",returnsDue:"/operations/dispatch?status=PENDING_RETURN",failedPartialAlerts:"/operations/batches#alerts",expenses:"/finance#expenses"}}}):Promise.resolve({data:{hubs:[],shops:[]}}));const client=new QueryClient({defaultOptions:{queries:{retry:false}}});render(<MemoryRouter><QueryClientProvider client={client}><Dashboard/></QueryClientProvider></MemoryRouter>);expect(await screen.findByText("400,000 MMK")).toBeInTheDocument();expect(screen.getByText("3 rider(s) not settled")).toBeInTheDocument();expect(screen.getByText("600,000 MMK")).toBeInTheDocument();expect(screen.getByText("7,000 MMK")).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:/Rider money awaiting settlement/i}));expect(window.location.pathname).toBeDefined();});});

describe("Dashboard failure recovery",()=>{it("replaces loading with an actionable error and retries",async()=>{apiMock.mockImplementation((path:string)=>path==="/master-data/dashboard"?Promise.reject(new Error("offline")):Promise.resolve({data:{hubs:[],shops:[]}}));const client=new QueryClient({defaultOptions:{queries:{retry:false}}});render(<MemoryRouter><QueryClientProvider client={client}><Dashboard/></QueryClientProvider></MemoryRouter>);expect(await screen.findByRole("alert")).toHaveTextContent("overview could not be loaded");apiMock.mockImplementation((path:string)=>path==="/master-data/dashboard"?Promise.resolve({data:{data:{totalParcels:2,delivered:1,pendingReturn:0,batches:[]}}}):Promise.resolve({data:{hubs:[],shops:[]}}));fireEvent.click(screen.getByRole("button",{name:"Try again"}));expect(await screen.findByText("2")).toBeInTheDocument();});});
