import {useMemo,useState} from "react";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {CalendarClock,ExternalLink} from "lucide-react";
import {useTranslation} from "react-i18next";
import {Link} from "react-router-dom";
import {useAuth} from "@/app/auth";
import {api} from "@/lib/api";

type ReturnStatus="FAILED"|"REJECTED"|"PENDING_RETURN"|"PARTIAL";
type ReturnItem={id:string;trackingNumber:string;status:ReturnStatus;returnDueAt:string|null;batch:{id:string;label:string};shop:{id:string;name:string}};
type ReturnQueue={items:ReturnItem[];summary:{count:number;totalRecoverableAmount:number}};
type DueFilter="all"|"due"|"overdue";
const statuses:ReturnStatus[]=["FAILED","REJECTED","PENDING_RETURN","PARTIAL"];
const readableRoles=["SUPERADMIN","OPERATIONS_MANAGER","FINANCE","AUDITOR"];
const statusKey=(status:ReturnStatus)=>status==="PENDING_RETURN"?"pendingReturn":status.toLowerCase();
const badge=(status:ReturnStatus)=>status==="FAILED"?"bg-rose-50 text-rose-700 dark:bg-rose-950/40 dark:text-rose-300":status==="REJECTED"?"bg-orange-50 text-orange-700 dark:bg-orange-950/40 dark:text-orange-300":status==="PARTIAL"?"bg-sky-50 text-sky-700 dark:bg-sky-950/40 dark:text-sky-300":"bg-amber-50 text-amber-700 dark:bg-amber-950/40 dark:text-amber-300";

export function OperationsReturnQueue(){
 const {t,i18n}=useTranslation();const {user}=useAuth();const qc=useQueryClient();
 const canRead=Boolean(user&&readableRoles.includes(user.role));const canExtend=user?.role==="SUPERADMIN"||user?.role==="OPERATIONS_MANAGER";
 const [status,setStatus]=useState<ReturnStatus|"ALL">("ALL");const [due,setDue]=useState<DueFilter>("all");const [editing,setEditing]=useState<ReturnItem|null>(null);const [days,setDays]=useState("1");const [reason,setReason]=useState("");const [message,setMessage]=useState("");
 const queue=useQuery({queryKey:["operations-return-queue"],queryFn:()=>api<ReturnQueue>("/finance/os-pending-returns").then(r=>r.data),enabled:canRead});
 const rows=useMemo(()=>{const now=Date.now();return(queue.data?.items??[]).filter(row=>status==="ALL"||row.status===status).filter(row=>{if(due==="all")return true;if(!row.returnDueAt)return false;return due==="overdue"?new Date(row.returnDueAt).getTime()<now:new Date(row.returnDueAt).getTime()>=now})},[queue.data?.items,status,due]);
 const extend=useMutation({mutationFn:()=>api(`/operations/parcels/${editing!.id}/return-extension`,{method:"POST",body:JSON.stringify({days:Number(days),reason:reason.trim()})}),onSuccess:async()=>{setEditing(null);setReason("");setDays("1");setMessage(t("returnExtensionSaved"));await Promise.all([qc.invalidateQueries({queryKey:["operations-return-queue"]}),qc.invalidateQueries({queryKey:["os-pending-returns"]}),qc.invalidateQueries({queryKey:["operations-batches"]})])},onError:e=>setMessage(e instanceof Error?e.message:t("loadError"))});
 if(!canRead)return null;
 return <section id="return-queue" className="mt-5 rounded-xl border border-black/5 bg-white p-4 shadow-sm dark:border-white/10 dark:bg-[#181a1d]">
  <div className="flex flex-wrap items-start justify-between gap-3"><div className="flex gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-amber-50 text-amber-700 dark:bg-amber-950/40"><CalendarClock size={19}/></div><div><h2 className="font-display text-base font-bold">{t("operationsReturnQueue")}</h2><p className="text-xs text-slate-500">{t("operationsReturnQueueDescription")}</p></div></div><Link to="/operations/dispatch?status=PENDING_RETURN" className="flex items-center gap-1.5 text-xs font-bold text-[#0787df]">{t("openDispatchQueue")}<ExternalLink size={13}/></Link></div>
  {message&&<p role="status" className="mt-3 text-sm font-semibold text-[#0787df]">{message}</p>}
  <div className="mt-4 flex flex-wrap gap-2" aria-label={t("returnStatusFilter")}><button className={filterClass(status==="ALL")} onClick={()=>setStatus("ALL")}>{t("all")} ({queue.data?.summary?.count??0})</button>{statuses.map(value=><button key={value} className={filterClass(status===value)} onClick={()=>setStatus(value)}>{t(statusKey(value))}</button>)}</div>
  <div className="mt-2 flex flex-wrap gap-2" aria-label={t("returnDueFilter")}>{(["all","due","overdue"] as DueFilter[]).map(value=><button key={value} className={filterClass(due===value)} onClick={()=>setDue(value)}>{t(value==="all"?"allDueStates":value)}</button>)}</div>
  {queue.isLoading?<p className="py-8 text-center text-sm text-slate-400">{t("loading")}</p>:queue.isError?<div className="py-8 text-center"><p className="text-sm text-rose-500">{t("returnQueueLoadError")}</p><button className="mt-2 text-sm font-bold text-[#0787df]" onClick={()=>void queue.refetch()}>{t("retry")}</button></div>:!rows.length?<p className="py-8 text-center text-sm text-slate-400">{t("noReturnsMatch")}</p>:<div className="mt-4 overflow-x-auto"><table className="w-full min-w-[780px] text-left text-xs"><thead><tr className="border-b text-[10px] uppercase tracking-wider text-slate-400 dark:border-white/10"><th className="pb-2">{t("tracking")}</th><th className="pb-2">{t("batch")}</th><th className="pb-2">{t("onlineShop")}</th><th className="pb-2">{t("status")}</th><th className="pb-2">{t("returnDue")}</th><th className="pb-2 text-right">{t("action")}</th></tr></thead><tbody>{rows.map(row=>{const overdue=Boolean(row.returnDueAt&&new Date(row.returnDueAt).getTime()<Date.now());return <tr key={row.id} className="border-b dark:border-white/5"><td className="py-3 font-bold">{row.trackingNumber}</td><td>{row.batch.label}</td><td>{row.shop.name}</td><td><span className={`rounded-full px-2 py-1 font-bold ${badge(row.status)}`}>{t(statusKey(row.status))}</span></td><td>{row.returnDueAt?<span className={overdue?"font-bold text-rose-600":"text-slate-600 dark:text-slate-300"}>{new Intl.DateTimeFormat(i18n.resolvedLanguage==="my"?"my-MM":"en-GB",{dateStyle:"medium"}).format(new Date(row.returnDueAt))} · {t(overdue?"overdue":"due")}</span>:<span className="text-slate-400">{t("noDueDate")}</span>}</td><td><div className="flex justify-end gap-2"><Link className="rounded-md border border-[#1598ef] px-2 py-1 font-bold text-[#0787df]" to={`/operations/dispatch?batchId=${encodeURIComponent(row.batch.id)}&status=${row.status}`}>{t("openInDispatch")}</Link>{canExtend&&row.status==="PENDING_RETURN"&&row.returnDueAt&&<button className="rounded-md bg-[#1598ef] px-2 py-1 font-bold text-white" onClick={()=>{setEditing(row);setMessage("")}}>{t("extendReturn")}</button>}</div></td></tr>})}</tbody></table></div>}
  {editing&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/55 p-4"><form aria-label={t("extendReturnTitle")} onSubmit={e=>{e.preventDefault();extend.mutate()}} className="w-full max-w-md rounded-2xl bg-white p-6 text-slate-950 shadow-2xl dark:bg-[#181a1d] dark:text-white"><h3 className="text-xl font-bold">{t("extendReturnTitle")}</h3><p className="mt-2 text-sm text-slate-500">{editing.trackingNumber} · {t("currentDueDate",{date:new Date(editing.returnDueAt!).toLocaleDateString()})}</p><label className="mt-5 block text-sm font-semibold">{t("extensionDays")}<input aria-label={t("extensionDays")} required type="number" min="1" max="30" value={days} onChange={e=>setDays(e.target.value)} className="mt-1 w-full rounded-xl border bg-transparent px-3 py-2"/></label><label className="mt-4 block text-sm font-semibold">{t("extensionReason")}<textarea aria-label={t("extensionReason")} required minLength={2} value={reason} onChange={e=>setReason(e.target.value)} className="mt-1 min-h-24 w-full rounded-xl border bg-transparent px-3 py-2"/></label><div className="mt-5 flex justify-end gap-2"><button type="button" className="rounded-xl border px-4 py-2 text-sm font-bold" onClick={()=>setEditing(null)}>{t("cancel")}</button><button disabled={extend.isPending||Number(days)<1||Number(days)>30||reason.trim().length<2} className="rounded-xl bg-[#1598ef] px-4 py-2 text-sm font-bold text-white disabled:opacity-40">{extend.isPending?t("loading"):t("saveExtension")}</button></div></form></div>}
 </section>
}
function filterClass(active:boolean){return`rounded-full border px-3 py-1.5 text-xs font-bold transition ${active?"border-[#1598ef] bg-[#eaf6ff] text-[#0787df] dark:bg-[#1598ef]/15":"border-slate-200 text-slate-500 dark:border-white/10"}`}
