import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useForm } from "react-hook-form";
import { Pencil, Power, RotateCcw, UserPlus, X } from "lucide-react";
import { useTranslation } from "react-i18next";
import { api } from "@/lib/api";

type Role = "SUPERADMIN" | "OPERATIONS_MANAGER" | "FINANCE" | "DISPATCHER" | "RIDER" | "AUDITOR";
type Hub = { id: string; name: string };
type User = { id:string;name:string;username:string;email:string;role:Role;active:boolean;hubId:string|null;hub:Hub|null };
type UserPage = { items:User[];pagination:{page:number;pageSize:number;total:number;totalPages:number} };
type Form = { name:string;username:string;email:string;password:string;role:Role;hubId:string };
const roles:Role[]=["SUPERADMIN","OPERATIONS_MANAGER","FINANCE","DISPATCHER","RIDER","AUDITOR"];
const control="w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus-visible:ring-2 focus-visible:ring-[#1598ef] dark:border-white/10 dark:bg-[#121416]";
const defaults:Form={name:"",username:"",email:"",password:"",role:"OPERATIONS_MANAGER",hubId:""};
const needsHub=(role:Role)=>!["SUPERADMIN","AUDITOR"].includes(role);

export function UserAdminSection({hubs}:{hubs:Hub[]}){
 const {t}=useTranslation(); const qc=useQueryClient();
 const [page,setPage]=useState(1); const [search,setSearch]=useState(""); const [role,setRole]=useState(""); const [active,setActive]=useState("");
 const [editing,setEditing]=useState<User|null>(null); const [confirm,setConfirm]=useState<{kind:"status"|"password";user:User}|null>(null); const [newPassword,setNewPassword]=useState(""); const [message,setMessage]=useState("");
 const {register,handleSubmit,watch,reset,formState:{errors,isSubmitting}}=useForm<Form>({defaultValues:defaults});
 const params=new URLSearchParams({page:String(page),pageSize:"10"}); if(search.trim())params.set("search",search.trim());if(role)params.set("role",role);if(active)params.set("active",active);
 const users=useQuery({queryKey:["users",page,search,role,active],queryFn:()=>api<UserPage>(`/users?${params}`).then(r=>r.data),placeholderData:p=>p});
 const save=useMutation({mutationFn:(form:Form)=>editing?api(`/users/${editing.id}`,{method:"PATCH",body:JSON.stringify({name:form.name,username:form.username,email:form.email,role:form.role,hubId:needsHub(form.role)?form.hubId:null})}):api("/users",{method:"POST",body:JSON.stringify({...form,hubId:needsHub(form.role)?form.hubId:null})}),onSuccess:async()=>{setMessage(t(editing?"userUpdated":"userCreated"));setEditing(null);reset(defaults);await qc.invalidateQueries({queryKey:["users"]})},onError:e=>setMessage(e instanceof Error?e.message:t("loadError"))});
 const action=useMutation({mutationFn:()=>{if(!confirm)throw new Error();return confirm.kind==="status"?api(`/users/${confirm.user.id}/status`,{method:"PATCH",body:JSON.stringify({active:!confirm.user.active})}):api(`/users/${confirm.user.id}/password-reset`,{method:"POST",body:JSON.stringify({password:newPassword})})},onSuccess:async()=>{setMessage(t(confirm?.kind==="status"?"userStatusUpdated":"userPasswordReset"));setConfirm(null);setNewPassword("");await qc.invalidateQueries({queryKey:["users"]})},onError:e=>setMessage(e instanceof Error?e.message:t("loadError"))});
 const beginEdit=(u:User)=>{setEditing(u);reset({name:u.name,username:u.username,email:u.email,password:"",role:u.role,hubId:u.hubId??""})}; const selectedRole=watch("role");
 return <section className="rounded-2xl bg-white p-5 shadow-sm dark:bg-[#181a1d] lg:col-span-2" aria-labelledby="users-heading">
  <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 id="users-heading" className="font-display text-xl font-bold">{t("userManagement")}</h2><p className="mt-1 text-sm text-slate-500">{t("userManagementDescription")}</p></div>{editing&&<button className="inline-flex items-center gap-1 text-sm font-semibold text-slate-500" onClick={()=>{setEditing(null);reset(defaults)}}><X size={16}/>{t("cancelEdit")}</button>}</div>
  {message&&<p role="status" className="mt-4 rounded-xl bg-sky-50 p-3 text-sm text-sky-700 dark:bg-sky-950/40 dark:text-sky-300">{message}</p>}
  <form className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-4" onSubmit={handleSubmit(v=>save.mutate(v))}>
   <label className="text-sm font-semibold">{t("name")}<input className={`${control} mt-1`} {...register("name",{required:true,minLength:2})}/>{errors.name&&<span className="text-xs text-rose-600">{t("minimumTwoCharacters")}</span>}</label>
   <label className="text-sm font-semibold">{t("username")}<input className={`${control} mt-1`} autoComplete="off" {...register("username",{required:true,pattern:/^[A-Za-z0-9._-]{3,50}$/})}/>{errors.username&&<span className="text-xs text-rose-600">{t("validUsernameRequired")}</span>}</label>
   <label className="text-sm font-semibold">{t("email")}<input className={`${control} mt-1`} type="email" autoComplete="off" {...register("email",{required:true})}/></label>
   {!editing&&<label className="text-sm font-semibold">{t("temporaryPassword")}<input className={`${control} mt-1`} type="password" autoComplete="new-password" {...register("password",{required:true,minLength:12,validate:v=>/[a-z]/.test(v)&&/[A-Z]/.test(v)&&/[0-9]/.test(v)})}/>{errors.password&&<span className="text-xs text-rose-600">{t("strongPasswordRequired")}</span>}</label>}
   <label className="text-sm font-semibold">{t("role")}<select className={`${control} mt-1`} {...register("role")}>{roles.map(r=><option key={r} value={r}>{t(`role_${r}`)}</option>)}</select></label>
   <label className="text-sm font-semibold">{t("hub")}<select className={`${control} mt-1`} disabled={!needsHub(selectedRole)} {...register("hubId",{validate:v=>!needsHub(selectedRole)||Boolean(v)})}><option value="">{needsHub(selectedRole)?t("selectHub"):t("organizationWide")}</option>{hubs.map(h=><option key={h.id} value={h.id}>{h.name}</option>)}</select>{errors.hubId&&<span className="text-xs text-rose-600">{t("hubRequiredForRole")}</span>}</label>
   <div className="flex items-end"><button disabled={isSubmitting||save.isPending} className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-[#1598ef] px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50"><UserPlus size={17}/>{t(editing?"saveUser":"createUser")}</button></div>
  </form>
  <div className="mt-7 flex flex-col gap-3 md:flex-row"><label className="flex-1 text-sm font-semibold">{t("searchUsers")}<input className={`${control} mt-1`} value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} type="search"/></label><label className="text-sm font-semibold">{t("role")}<select className={`${control} mt-1`} value={role} onChange={e=>{setRole(e.target.value);setPage(1)}}><option value="">{t("all")}</option>{roles.map(r=><option key={r} value={r}>{t(`role_${r}`)}</option>)}</select></label><label className="text-sm font-semibold">{t("status")}<select className={`${control} mt-1`} value={active} onChange={e=>{setActive(e.target.value);setPage(1)}}><option value="">{t("all")}</option><option value="true">{t("active")}</option><option value="false">{t("inactive")}</option></select></label></div>
  {users.isLoading?<p className="py-10 text-center text-sm text-slate-500" role="status">{t("loading")}</p>:users.isError?<div className="py-10 text-center"><p className="text-sm text-rose-600">{t("usersLoadError")}</p><button className="mt-3 font-bold text-[#0787df]" onClick={()=>void users.refetch()}>{t("retry")}</button></div>:!users.data?.items.length?<p className="py-10 text-center text-sm text-slate-500">{t("noUsersFound")}</p>:<div className="mt-4 grid gap-3">{users.data.items.map(u=><article key={u.id} className="grid gap-3 rounded-xl border border-slate-200 p-4 dark:border-white/10 md:grid-cols-[1.4fr_1fr_1fr_auto] md:items-center"><div><p className="font-bold">{u.name}</p><p className="text-xs text-slate-500">@{u.username} · {u.email}</p></div><div className="text-sm"><p>{t(`role_${u.role}`)}</p><p className="text-xs text-slate-500">{u.hub?.name??t("organizationWide")}</p></div><span className={`w-fit rounded-full px-2.5 py-1 text-xs font-bold ${u.active?"bg-emerald-100 text-emerald-700 dark:bg-emerald-950":"bg-slate-100 text-slate-600 dark:bg-white/10"}`}>{t(u.active?"active":"inactive")}</span><div className="flex gap-1"><button aria-label={t("editUserName",{name:u.name})} title={t("edit")} className="rounded-lg p-2 hover:bg-slate-100 dark:hover:bg-white/10" onClick={()=>beginEdit(u)}><Pencil size={17}/></button><button aria-label={t("resetUserPasswordName",{name:u.name})} title={t("resetPassword")} className="rounded-lg p-2 hover:bg-slate-100 dark:hover:bg-white/10" onClick={()=>setConfirm({kind:"password",user:u})}><RotateCcw size={17}/></button><button aria-label={t(u.active?"deactivateUserName":"activateUserName",{name:u.name})} title={t(u.active?"deactivate":"activate")} className="rounded-lg p-2 hover:bg-slate-100 dark:hover:bg-white/10" onClick={()=>setConfirm({kind:"status",user:u})}><Power size={17}/></button></div></article>)}</div>}
  {users.data&&users.data.pagination.totalPages>1&&<nav aria-label={t("userPagination")} className="mt-4 flex items-center justify-between text-sm"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>{t("previous")}</button><span>{t("pageOf",{page,total:users.data.pagination.totalPages})}</span><button disabled={page>=users.data.pagination.totalPages} onClick={()=>setPage(p=>p+1)}>{t("next")}</button></nav>}
  {confirm&&<div role="dialog" aria-modal="true" aria-labelledby="user-confirm-title" className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-xl dark:bg-[#181a1d]"><h3 id="user-confirm-title" className="text-lg font-bold">{t(confirm.kind==="status"?(confirm.user.active?"confirmDeactivateUser":"confirmActivateUser"):"confirmPasswordReset",{name:confirm.user.name})}</h3><p className="mt-2 text-sm text-slate-500">{t(confirm.kind==="password"?"passwordResetSessionNotice":"statusSessionNotice")}</p>{confirm.kind==="password"&&<label className="mt-4 block text-sm font-semibold">{t("newPassword")}<input className={`${control} mt-1`} type="password" autoComplete="new-password" value={newPassword} onChange={e=>setNewPassword(e.target.value)}/><span className="mt-1 block text-xs text-slate-500">{t("strongPasswordRequired")}</span></label>}<div className="mt-6 flex justify-end gap-2"><button className="rounded-xl px-4 py-2 text-sm font-bold" onClick={()=>{setConfirm(null);setNewPassword("")}}>{t("cancel")}</button><button disabled={action.isPending||(confirm.kind==="password"&&!(newPassword.length>=12&&/[a-z]/.test(newPassword)&&/[A-Z]/.test(newPassword)&&/[0-9]/.test(newPassword)))} className="rounded-xl bg-[#1598ef] px-4 py-2 text-sm font-bold text-white disabled:opacity-50" onClick={()=>action.mutate()}>{t("confirm")}</button></div></div></div>}
 </section>
}
