import { body, param, query } from "express-validator";
import { idempotencyKey, optionalHub, walletSplit } from "./shared.js";

export const osAccountsValidators = [query("shopId").optional().isString().trim().notEmpty(), query("hubId").optional().isString().trim().notEmpty()];
export const osAccountHistoryValidators = [param("shopId").isString().trim().notEmpty(), query("hubId").optional().isString().trim().notEmpty()];
export const cutoverAdjustmentValidators = [body("shopId").isString().trim().notEmpty(), body("hubId").isString().trim().notEmpty(), body("adjustment").isInt().toInt(), body("businessDate").isISO8601(), body("reason").isString().trim().isLength({ min: 3, max: 500 }), idempotencyKey];
export const osPaymentValidators = [body("shopId").isString().trim().notEmpty(), optionalHub, body("batchIds").isArray({ min: 1, max: 100 }), body("batchIds.*").isString().trim().notEmpty(), body("businessDate").isISO8601(), ...walletSplit, body("note").isString().trim().isLength({ min: 3, max: 500 }), body("reference").optional().isString().trim().isLength({ max: 150 }), idempotencyKey];
export const voidOsPaymentValidators = [param("id").isString().trim().notEmpty(), optionalHub, body("businessDate").isISO8601(), body("reason").isString().trim().isLength({ min: 3, max: 500 }), idempotencyKey];
export const replaceOsPaymentValidators = [param("id").isString().trim().notEmpty(), optionalHub, body("businessDate").isISO8601(), body("reason").isString().trim().isLength({ min: 3, max: 500 }), idempotencyKey, body("replacement").isObject(), body("replacement.shopId").isString().trim().notEmpty(), body("replacement.hubId").optional().isString().trim().notEmpty(), body("replacement.batchIds").isArray({ min: 1, max: 100 }), body("replacement.batchIds.*").isString().trim().notEmpty(), body("replacement.businessDate").isISO8601(), body("replacement.wallets").isObject(), body("replacement.wallets.cash").isInt({ min: 0 }), body("replacement.wallets.kbzPay").isInt({ min: 0 }), body("replacement.wallets.wavePay").isInt({ min: 0 }), body("replacement.note").isString().trim().isLength({ min: 3, max: 500 }), body("replacement.reference").optional().isString().trim().isLength({ max: 150 }), body("replacement.idempotencyKey").isString().trim().isLength({ min: 8, max: 100 })];
